services:
  core-service:
    build:
      context: core-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://database_diary:5432/postgres"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres"
    networks:
      - spring-cloud-network

  gateway-service:
    build:
      context: gateway-service
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    networks:
      - spring-cloud-network

  database:
    container_name: database_diary
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    networks:
      - spring-cloud-network

networks:
  spring-cloud-network:
    driver: bridge