server:
  port: 8082
  servlet:
    context-path: /upload

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
  instance:
    preferIpAddress: true

spring:
  application:
    name: upload-service
  kafka:
    bootstrap-servers: kafka:9092
  servlet:
    multipart:
      max-file-size: 10MB
  bucket:
    name: "diary-storage1"
    access-key-id: "YCAJEWglZhP2oogjWumME4a_J"
    secret-access-key: "YCNOF5mMoTev_5aMS4PDrYTdBcFnfKidHnmHA3sx"
