server:
  port: 8761

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: eureka-service