server:
  port: 8080

spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    access-secret: "testlbfeiwcbu029KWLGHIORHIORWHFFIEWOHR9FEWYFIEWHIW"
    refresh-secret: "knwlx023749032wwjdkjkshONIO3IomopMONUYVubiYUBIiu"
    life-time: 30m
    refresh-life-time: 30D

  mail:
    host: smtp.yandex.ru
    port: 465
    username: "Dm-minin05"
    password: "tsopuwkiyqqynzuo"
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
    sender:
      email: "Dm-minin05@yandex.ru"
      text: "Dm-minin05"

  patterns:
    email-pattern: "^[A-Z0-9._%+-]+@[A-Z0-9.-]+\\.[A-Z]{2,6}$"